namespace InvoiceBuilder.Application.DTOs;

public record ExcelInvoiceDto(
    string InvoiceNumber,
    DateOnly InvoiceDate,
    DateOnly ExpireDate,
    string CompanyName,
    string ContactName,
    string Address,
    string Postal,
    string City,
    string Country,
    string ChamberOfCommerce,
    string VATID,
    string Row1Description,
    decimal Row1VatRate,
    decimal Row1Cost,
    string Row2Description,
    decimal Row2VatRate,
    decimal Row2Cost,
    string Row3Description,
    decimal Row3VatRate,
    decimal Row3Cost,
    string Row4Description,
    decimal Row4VatRate,
    decimal Row4Cost,
    string Row5Description,
    decimal Row5VatRate,
    decimal Row5Cost,
    string Row6Description,
    decimal Row6VatRate,
    decimal Row6Cost,
    string Currency = "EUR"
);